### PR TITLE
Add reset font style and text align options

### PR DESCRIPTION
**Pull request by EliteUser**
Sometimes when modifying an existing presentation, it has some built-in font styles, which i want to override explicitly.
For examle, I have some presentation and I want to add a text box using slide.addText(). When I see the result, the added text is bold and centered, so I want to set fontBold: false and textAlign: 'left' to get proper style.

### CODE REVIEW

**Review by heavysixer — COMMENTED** [review]
This looks good to me. Sorry for the late reply. @gregdolley  what do you think?

**Comment by heavysixer** [comment]
Is there any way to add a test for this or does it need to be manual inspection only?

**Comment by EliteUser** [comment]
I don`t know if it can be tested, think manual inspection only, because of unknown styles of pptx template.

**Comment by heavysixer** [comment]
@EliteUser sorry for the delay we're still discussing this internally.

**Pull request merged**
